# Description:
#   Displays all the developped commands
#
# Note
#   (!) Must be updated manually (!)

#'use strict'

module.exports = (robot) ->
    robot.hear /(help|aide|\?)/i, (res) ->
        res.reply ""
        res.reply "===== TRIAPLAT related stuff =============================="
        res.reply "jobs                : List all the jobs"
        res.reply "fts                 : List all the file transfers"
        res.reply "boxes               : List all the boxes"
        res.reply "                    : aliases : boxs"
        res.reply "entries             : Displays the entry point of all the registered contributors"
        res.reply "XXX entry           : Displays the entry point of the contributor XXX"
        res.reply "jobs like XX        : Lists all the jobs whose name are containing XX"
        res.reply "fts like XX         : Lists all the fts whose name are containing XX"
        res.reply "boxes like XX       : Lists all the boxes whose name are containing XX"
        res.reply "XX job desc         : Displays the description of the job named XX"
        res.reply "                    : aliases : job description,job details"
        res.reply "XXX triggers        : List the jobs that are in the starting condition of the job XX"
        res.reply "                    : aliases : declenche, déclenche"
        res.reply "XX cascade          : List all the jobs that are in the starting condition of the job XX"
        res.reply "XX cascade Y        : List all the jobs that are in the starting condition of the job XX and do it on Y generations"
        res.reply "XXX childs          : List all the jobs whose box is XX"
        res.reply "                    : aliases : XX kids"
        res.reply "XX family           : Displays the while job hierarchy for the XX job (with the details for each job)"
        res.reply "jobs by calendar XX : List all the jobs whose calender is XX"
        res.reply ""
        res.reply "===== AUTOSYS related stuff =============================="
        res.reply "calendars           : List all the autosys calendars"
        res.reply "                    : aliases : calendriers"
        res.reply "XX calendar desc    : Displays the XXX calendar's description"
        res.reply "                    : aliases : XX cal desc, XX calendrier desc"
        res.reply "XX call             : Displays the script called by the autosys script XX"
        res.reply "                    : aliases : XX calls"
        res.reply "XX called           : Displays the autosys script that contains the XX chain in its called script"
        res.reply ""
        res.reply "===== IDF (referentielCft) ==============================="
        res.reply "cft ids              : List all the referentielCft's IDFs"
        res.reply "                     : aliases : cfts"
        res.reply "cft like XX          : Lists all the IDF that are containing XX"
        res.reply "XX cft desc          : Displays the description of the CFT named XX"
        res.reply "                     : aliases : cft description,cft details"
        res.reply "cft sending XX       : Lists all the IDFs that are sending the file XX"
        res.reply "cft categories       : Lists all the different referentielCft file' categories"
        res.reply "cft from category XX : Lists all the IDFs with the category XX"
        res.reply ""
        res.reply "===== Shortcuts =========================================="
        res.reply "XX desc             : Tries to recognize the type of data you're looking for and displays it's description"
        res.reply "                    : so far only autosys calendars, jobs, boxes and IDF are recognized"
        res.reply ""
        res.reply "===== ISL related stuff =================================="
        res.reply "XX c_ids            : List all the contributor's registered C_IDs"
        res.reply "                    : aliases : calendriers"
        res.reply "contribs            : List of contributors that are registered"
        res.reply ""
        res.reply "===== SQL related stuff =================================="
        res.reply "sql list            : List all the registered SQL requests"
        res.reply "                    : aliases : ls"
        res.reply "sql get XX          : Displays the XX SQL request"
        res.reply "                    : aliases : gimme, display"
